# ベースイメージとしてUbuntu 22.04 LTSを使用
FROM nvidia/cuda:12.3.0-runtime-ubuntu22.04

# 環境変数の設定
ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=humble

# 基本的な依存関係のインストール
RUN apt-get update && apt-get install -y \
    curl \
    gnupg2 \
    lsb-release \
    wget \
    build-essential \
    cmake \
    git \
    vim \
    python3-pip \
    portaudio19-dev \
    tmux \
    x11-apps \
    x11-xserver-utils \
    mesa-utils \
    unzip \
    software-properties-common \
    libgtk2.0-dev \
    pkg-config \
    libcanberra-gtk-module \
    && rm -rf /var/lib/apt/lists/*

# YOLOv8のインストール
RUN pip3 install ultralytics

# ROS2のインストール
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - \
    && echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2-latest.list \
    && apt-get update && apt-get install -y \
    ros-humble-desktop \
    ros-humble-turtlebot3-gazebo \
    ros-humble-turtlebot3-cartographer \
    ros-humble-turtlebot3-navigation2 \
    ros-humble-turtlebot3-teleop \
    ros-humble-ur-client-library \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-rosinstall \
    python3-vcstool \
    && rosdep init \
    && rosdep update

# 公開鍵をダウンロードしてシステムのキーリングに追加
RUN wget -O - https://packages.osrfoundation.org/gazebo.key | gpg --dearmor > /etc/apt/trusted.gpg.d/gazebo-archive-keyring.gpg

# Gazeboのリポジトリを追加
RUN echo "deb [signed-by=/etc/apt/trusted.gpg.d/gazebo-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" > /etc/apt/sources.list.d/gazebo-stable.list

# Update package information and install the necessary packages
RUN apt-get update && apt-get install -y \
    gazebo \
    ros-humble-gazebo-ros-pkgs \
    ros-humble-gazebo-ros2-control \
    wget \
    gnupg2 \
    lsb-release \
    sudo \
    ros-humble-robot-state-publisher \
    ros-humble-joint-state-publisher \
    ros-humble-rviz2 \
    ros-humble-teleop-twist-keyboard \
    ros-humble-image-transport \
    ros-humble-cv-bridge \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-raspimouse-sim \
    ros-humble-raspimouse-slam-navigation \
    ros-humble-teleop-twist-keyboard \
    && rm -rf /var/lib/apt/lists/*

# Pythonパッケージのインストール
RUN pip3 install --upgrade pip
RUN pip3 install \
    torch \
    torchvision \
    torchaudio \
    pyyaml \
    numpy \
    matplotlib \
    pillow \
    opencv-python-headless \
    stable-baselines3 \
    gym \
    rospkg \
    roslibpy \
    speechrecognition \
    pyaudio

# opencv-python-headlessのアンインストールとopencv-pythonのインストール
RUN pip uninstall -y opencv-python-headless \
    && pip install opencv-python

# YOLOv8のインストール（重複しないように確認）
RUN pip3 install ultralytics

# 不要な重複するパッケージを削除
RUN apt-get update && apt-get install -y \
    libxkbcommon-x11-0 \
    libglu1-mesa-dev \
    && rm -rf /var/lib/apt/lists/*

# object_detection_pkgのセットアップ
COPY object_detection_pkg /root/ros2_ws/src/object_detection_pkg

# ワークスペースのビルド
#RUN . /opt/ros/${ROS_DISTRO}/setup.sh && colcon build --symlink-install

# Visual Studio Codeのインストール
#RUN wget -qO /tmp/vscode.deb https://update.code.visualstudio.com/latest/linux-deb-x64/stable \
#    && apt-get update \
#    && apt-get install -y /tmp/vscode.deb \
#    && rm /tmp/vscode.deb

CMD ["bash"]

